{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "Inventory",
    "description": "Enable user to perform CRUD operations on inventory.",
    "license": {
      "name": "MIT",
      "url": "http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT"
    }
  },
  "host": "localhost:8000",
  "basePath": "/core/inventory",
  "securityDefinitions": {
    "auth": {
      "type": "oauth2",
      "flow": "implicit",
      "authorizationUrl": "http://localhost:8000/core/inventory",
      "scopes": {}
    }
  },
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/getAll": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "getAll",
        "tags": [
          "Misc"
        ],
        "operationId": "getAll",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/GetAllRequest"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "tenantId",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "userId",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "email",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Origin",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/GetAllResponse"
            },
            "examples": {
              "application/json": {
                "status": 200,
                "message": "All data retrieved",
                "data": [
                  {
                    "id": 1,
                    "effBegin": "2017-10-01",
                    "effEnd": "2018-10-01",
                    "code": "RW1",
                    "name": "Laptop",
                    "description": "Blahblahblahchocoblah",
                    "type": "Tech"
                  }
                ]
              }
            }
          }
        },
        "security": [
          {
            "auth": []
          }
        ],
        "x-unitTests": [
          {
            "request": {
              "method": "POST",
              "uri": "/getAll",
              "headers": {
                "Content-Type": "application/json",
                "tenantId": "1000000000",
                "userId": "1",
                "email": "user1@mail.com",
                "Authorization": "Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJteWRvY2tlciIsInN1YiI6InVzZXIxQG1haWwuY29tIiwiYXVkIjoiZHJpZmUubXlkb2NrZXIuY29tIiwiZXhwIjoxNTA3NjAxNjQ5LCJuYmYiOjE1MDc1MTUyNDksImlhdCI6MTUwNzUxNTI0OSwianRpIjoidXNlcjFAbWFpbC5jb21fMTUwNzUxNTI0OSIsInRlbmFudElkIjoxMDAwMDAwMDAwLCJ1c2VySWQiOjEsImVtYWlsIjoidXNlcjFAbWFpbC5jb20ifQ.R-8KDpr_4cg114o2IV49uyj59ab7iwlFwfIlxTHD2mBo7t2Eo6kuYZAigIJLLKwwwD7yJ3IMNhCgmuPfsx5Znt997ylRR8QDncIrEtu2fNQQa0sTTeXQ5mZhHEjz5zznaMgqSYhZxzLOn5cKET6fz3cCJto4HJsorZx9e3xdhXWtVZFzPRDH6924ZVTfYfo9bYl-rX_U9Ke2O8ktKEHu0YovJ4-sIhTWO4zGgaHYyi5AHNGZxw5YAHCWxrzEnr2lL69JuYpV6ncxylWY0MmZ6Tft1hdvf54mVARO-JdFIDK5VfqNReeWDx-6RkpKC8jaTePo320mVW1eQcPTMfGiSQ",
                "Origin": "drife.mydocker.com"
              },
              "body": "{\n\t\"companyId\": 1900000000\n}"
            },
            "expectedResponse": {
              "x-allowExtraHeaders": true,
              "x-bodyMatchMode": "RAW",
              "x-arrayOrderedMatching": false,
              "x-arrayCheckCount": false,
              "x-matchResponseSchema": true,
              "headers": {
                "Access-Control-Allow-Origin": "*",
                "Cache-Control": "no-cache, private",
                "Connection": "keep-alive",
                "Content-Language": "en",
                "Content-Type": "application/json",
                "Date": "Mon, 09 Oct 2017 09:29:14 GMT",
                "Server": "nginx",
                "Transfer-Encoding": "chunked",
                "Via": "kong/0.11.0",
                "X-Kong-Proxy-Latency": "0",
                "X-Kong-Upstream-Latency": "80",
                "X-Powered-By": "PHP/7.1.9"
              },
              "body": "{\"status\":200,\"message\":\"All data retrieved\",\"data\":[{\"id\":1,\"effBegin\":\"2017-10-01\",\"effEnd\":\"2018-10-01\",\"code\":\"RW1\",\"name\":\"Laptop\",\"description\":\"Blahblahblahchocoblah\",\"type\":\"Tech\"}]}"
            },
            "x-testShouldPass": true,
            "x-testEnabled": true,
            "x-testName": "getAll",
            "x-testDescription": "TODO: Add Description"
          }
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/getOne": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "getOne",
        "tags": [
          "Misc"
        ],
        "operationId": "getOne",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/GetOneRequest"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "tenantId",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "userId",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "email",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Origin",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/GetOneResponse"
            },
            "examples": {
              "application/json": {
                "status": 200,
                "message": "Data retrieved",
                "data": {
                  "id": 1,
                  "effBegin": "2017-10-01",
                  "effEnd": "2018-10-01",
                  "code": "RW1",
                  "name": "Laptop",
                  "description": "Blahblahblahchocoblah",
                  "type": "Tech"
                }
              }
            }
          }
        },
        "security": [
          {
            "auth": []
          }
        ],
        "x-unitTests": [
          {
            "request": {
              "method": "POST",
              "uri": "/getOne",
              "headers": {
                "Content-Type": "application/json",
                "tenantId": "1000000000",
                "userId": "1",
                "email": "user1@mail.com",
                "Authorization": "Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJteWRvY2tlciIsInN1YiI6InVzZXIxQG1haWwuY29tIiwiYXVkIjoiZHJpZmUubXlkb2NrZXIuY29tIiwiZXhwIjoxNTA3NjAxNjQ5LCJuYmYiOjE1MDc1MTUyNDksImlhdCI6MTUwNzUxNTI0OSwianRpIjoidXNlcjFAbWFpbC5jb21fMTUwNzUxNTI0OSIsInRlbmFudElkIjoxMDAwMDAwMDAwLCJ1c2VySWQiOjEsImVtYWlsIjoidXNlcjFAbWFpbC5jb20ifQ.R-8KDpr_4cg114o2IV49uyj59ab7iwlFwfIlxTHD2mBo7t2Eo6kuYZAigIJLLKwwwD7yJ3IMNhCgmuPfsx5Znt997ylRR8QDncIrEtu2fNQQa0sTTeXQ5mZhHEjz5zznaMgqSYhZxzLOn5cKET6fz3cCJto4HJsorZx9e3xdhXWtVZFzPRDH6924ZVTfYfo9bYl-rX_U9Ke2O8ktKEHu0YovJ4-sIhTWO4zGgaHYyi5AHNGZxw5YAHCWxrzEnr2lL69JuYpV6ncxylWY0MmZ6Tft1hdvf54mVARO-JdFIDK5VfqNReeWDx-6RkpKC8jaTePo320mVW1eQcPTMfGiSQ",
                "Origin": "drife.mydocker.com"
              },
              "body": "{\n\t\"companyId\": 1900000000,\n\t\"id\": 1\n}"
            },
            "expectedResponse": {
              "x-allowExtraHeaders": true,
              "x-bodyMatchMode": "RAW",
              "x-arrayOrderedMatching": false,
              "x-arrayCheckCount": false,
              "x-matchResponseSchema": true,
              "headers": {
                "Access-Control-Allow-Origin": "*",
                "Cache-Control": "no-cache, private",
                "Connection": "keep-alive",
                "Content-Language": "en",
                "Content-Type": "application/json",
                "Date": "Mon, 09 Oct 2017 09:29:29 GMT",
                "Server": "nginx",
                "Transfer-Encoding": "chunked",
                "Via": "kong/0.11.0",
                "X-Kong-Proxy-Latency": "0",
                "X-Kong-Upstream-Latency": "90",
                "X-Powered-By": "PHP/7.1.9"
              },
              "body": "{\"status\":200,\"message\":\"Data retrieved\",\"data\":{\"id\":1,\"effBegin\":\"2017-10-01\",\"effEnd\":\"2018-10-01\",\"code\":\"RW1\",\"name\":\"Laptop\",\"description\":\"Blahblahblahchocoblah\",\"type\":\"Tech\"}}"
            },
            "x-testShouldPass": true,
            "x-testEnabled": true,
            "x-testName": "getOne",
            "x-testDescription": "TODO: Add Description"
          }
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/save": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "save",
        "tags": [
          "Misc"
        ],
        "operationId": "save",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/SaveRequest"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "tenantId",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "userId",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "email",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Origin",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/SaveResponse"
            },
            "examples": {
              "application/json": {
                "status": 200,
                "message": "Data saved",
                "data": {
                  "id": 1
                }
              }
            }
          }
        },
        "security": [
          {
            "auth": []
          }
        ],
        "x-unitTests": [
          {
            "request": {
              "method": "POST",
              "uri": "/save",
              "headers": {
                "Content-Type": "application/json",
                "tenantId": "1000000000",
                "userId": "1",
                "email": "user1@mail.com",
                "Authorization": "Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJteWRvY2tlciIsInN1YiI6InVzZXIxQG1haWwuY29tIiwiYXVkIjoiZHJpZmUubXlkb2NrZXIuY29tIiwiZXhwIjoxNTA3NjAxNjQ5LCJuYmYiOjE1MDc1MTUyNDksImlhdCI6MTUwNzUxNTI0OSwianRpIjoidXNlcjFAbWFpbC5jb21fMTUwNzUxNTI0OSIsInRlbmFudElkIjoxMDAwMDAwMDAwLCJ1c2VySWQiOjEsImVtYWlsIjoidXNlcjFAbWFpbC5jb20ifQ.R-8KDpr_4cg114o2IV49uyj59ab7iwlFwfIlxTHD2mBo7t2Eo6kuYZAigIJLLKwwwD7yJ3IMNhCgmuPfsx5Znt997ylRR8QDncIrEtu2fNQQa0sTTeXQ5mZhHEjz5zznaMgqSYhZxzLOn5cKET6fz3cCJto4HJsorZx9e3xdhXWtVZFzPRDH6924ZVTfYfo9bYl-rX_U9Ke2O8ktKEHu0YovJ4-sIhTWO4zGgaHYyi5AHNGZxw5YAHCWxrzEnr2lL69JuYpV6ncxylWY0MmZ6Tft1hdvf54mVARO-JdFIDK5VfqNReeWDx-6RkpKC8jaTePo320mVW1eQcPTMfGiSQ",
                "Origin": "drife.mydocker.com"
              },
              "body": "{\n\t\"companyId\": 1900000000,\n\t\"effBegin\": \"2017-10-1\",\n\t\"effEnd\": \"2018-10-1\",\n\t\"code\": \"RW1\",\n\t\"name\": \"Laptop\",\n\t\"description\": \"Blahblahblahchocoblah\",\n\t\"type\": \"Tech\"\n}"
            },
            "expectedResponse": {
              "x-allowExtraHeaders": true,
              "x-bodyMatchMode": "RAW",
              "x-arrayOrderedMatching": false,
              "x-arrayCheckCount": false,
              "x-matchResponseSchema": true,
              "headers": {
                "Access-Control-Allow-Origin": "*",
                "Cache-Control": "no-cache, private",
                "Connection": "keep-alive",
                "Content-Language": "en",
                "Content-Type": "application/json",
                "Date": "Mon, 09 Oct 2017 09:28:16 GMT",
                "Server": "nginx",
                "Transfer-Encoding": "chunked",
                "Via": "kong/0.11.0",
                "X-Kong-Proxy-Latency": "0",
                "X-Kong-Upstream-Latency": "608",
                "X-Powered-By": "PHP/7.1.9"
              },
              "body": "{\"status\":200,\"message\":\"Data saved\",\"data\":{\"id\":1}}"
            },
            "x-testShouldPass": true,
            "x-testEnabled": true,
            "x-testName": "save",
            "x-testDescription": "TODO: Add Description"
          }
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/update": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "update",
        "tags": [
          "Misc"
        ],
        "operationId": "update",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/UpdateRequest"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "tenantId",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "userId",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "email",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Origin",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/UpdateResponse"
            },
            "examples": {}
          }
        },
        "security": [
          {
            "auth": []
          }
        ],
        "x-unitTests": [],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/delete": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "delete",
        "tags": [
          "Misc"
        ],
        "operationId": "delete",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/DeleteRequest"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "tenantId",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "userId",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "email",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Origin",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/DeleteResponse"
            },
            "examples": {}
          }
        },
        "security": [
          {
            "auth": []
          }
        ],
        "x-unitTests": [],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    }
  },
  "definitions": {
    "GetAllRequest": {
      "title": "getAllRequest",
      "example": {
        "companyId": 1900000000
      },
      "type": "object",
      "properties": {
        "companyId": {
          "description": "",
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "companyId"
      ]
    },
    "GetAllResponse": {
      "title": "getAllResponse",
      "example": {
        "status": 200,
        "message": "All data retrieved",
        "data": [
          {
            "id": 1,
            "effBegin": "2017-10-01",
            "effEnd": "2018-10-01",
            "code": "RW1",
            "name": "Laptop",
            "description": "Blahblahblahchocoblah",
            "type": "Tech"
          }
        ]
      },
      "type": "object",
      "properties": {
        "status": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "description": "",
          "type": "string"
        },
        "data": {
          "description": "",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Datum"
          }
        }
      },
      "required": [
        "status",
        "message",
        "data"
      ]
    },
    "Datum": {
      "title": "Datum",
      "type": "object",
      "properties": {
        "id": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "effBegin": {
          "description": "",
          "type": "string"
        },
        "effEnd": {
          "description": "",
          "type": "string"
        },
        "code": {
          "description": "",
          "type": "string"
        },
        "name": {
          "description": "",
          "type": "string"
        },
        "description": {
          "description": "",
          "type": "string"
        },
        "type": {
          "description": "",
          "type": "string"
        }
      },
      "required": [
        "id",
        "effBegin",
        "effEnd",
        "code",
        "name",
        "description",
        "type"
      ]
    },
    "GetOneRequest": {
      "title": "getOneRequest",
      "example": {
        "companyId": 1900000000,
        "id": 1
      },
      "type": "object",
      "properties": {
        "companyId": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "id": {
          "description": "",
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "companyId",
        "id"
      ]
    },
    "GetOneResponse": {
      "title": "getOneResponse",
      "example": {
        "status": 200,
        "message": "Data retrieved",
        "data": {
          "id": 1,
          "effBegin": "2017-10-01",
          "effEnd": "2018-10-01",
          "code": "RW1",
          "name": "Laptop",
          "description": "Blahblahblahchocoblah",
          "type": "Tech"
        }
      },
      "type": "object",
      "properties": {
        "status": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "description": "",
          "type": "string"
        },
        "data": {
          "$ref": "#/definitions/Data"
        }
      },
      "required": [
        "status",
        "message",
        "data"
      ]
    },
    "Data": {
      "title": "Data",
      "type": "object",
      "properties": {
        "id": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "effBegin": {
          "description": "",
          "type": "string"
        },
        "effEnd": {
          "description": "",
          "type": "string"
        },
        "code": {
          "description": "",
          "type": "string"
        },
        "name": {
          "description": "",
          "type": "string"
        },
        "description": {
          "description": "",
          "type": "string"
        },
        "type": {
          "description": "",
          "type": "string"
        }
      },
      "required": [
        "id",
        "effBegin",
        "effEnd",
        "code",
        "name",
        "description",
        "type"
      ]
    },
    "SaveRequest": {
      "title": "saveRequest",
      "example": {
        "companyId": 1900000000,
        "effBegin": "2017-10-1",
        "effEnd": "2018-10-1",
        "code": "RW1",
        "name": "Laptop",
        "description": "Blahblahblahchocoblah",
        "type": "Tech"
      },
      "type": "object",
      "properties": {
        "companyId": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "effBegin": {
          "description": "",
          "type": "string"
        },
        "effEnd": {
          "description": "",
          "type": "string"
        },
        "code": {
          "description": "",
          "type": "string"
        },
        "name": {
          "description": "",
          "type": "string"
        },
        "description": {
          "description": "",
          "type": "string"
        },
        "type": {
          "description": "",
          "type": "string"
        }
      },
      "required": [
        "companyId",
        "effBegin",
        "effEnd",
        "code",
        "name",
        "description",
        "type"
      ]
    },
    "SaveResponse": {
      "title": "saveResponse",
      "example": {
        "status": 200,
        "message": "Data saved",
        "data": {
          "id": 1
        }
      },
      "type": "object",
      "properties": {
        "status": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "description": "",
          "type": "string"
        },
        "data": {
          "$ref": "#/definitions/Data8"
        }
      },
      "required": [
        "status",
        "message",
        "data"
      ]
    },
    "Data8": {
      "title": "Data8",
      "type": "object",
      "properties": {
        "id": {
          "description": "",
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "id"
      ]
    },
    "UpdateRequest": {
      "title": "updateRequest",
      "example": {
        "companyId": 1900000000,
        "id": 1,
        "effBegin": "2017-10-1",
        "effEnd": "2018-10-1",
        "code": "LP1",
        "name": "Laptop",
        "description": "Blahblahblahchocoblah",
        "type": "Tech"
      },
      "type": "object",
      "properties": {
        "companyId": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "id": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "effBegin": {
          "description": "",
          "type": "string"
        },
        "effEnd": {
          "description": "",
          "type": "string"
        },
        "code": {
          "description": "",
          "type": "string"
        },
        "name": {
          "description": "",
          "type": "string"
        },
        "description": {
          "description": "",
          "type": "string"
        },
        "type": {
          "description": "",
          "type": "string"
        }
      },
      "required": [
        "companyId",
        "id",
        "effBegin",
        "effEnd",
        "code",
        "name",
        "description",
        "type"
      ]
    },
    "UpdateResponse": {
      "title": "updateResponse",
      "type": "object",
      "properties": {
        "status": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "description": "",
          "type": "string"
        },
        "data": {
          "description": "",
          "type": "string"
        }
      },
      "required": [
        "status",
        "message",
        "data"
      ]
    },
    "DeleteRequest": {
      "title": "deleteRequest",
      "example": {
        "companyId": 1900000000,
        "id": 1
      },
      "type": "object",
      "properties": {
        "companyId": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "id": {
          "description": "",
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "companyId",
        "id"
      ]
    },
    "DeleteResponse": {
      "title": "deleteResponse",
      "type": "object",
      "properties": {
        "status": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "description": "",
          "type": "string"
        },
        "data": {
          "description": "",
          "type": "string"
        }
      },
      "required": [
        "status",
        "message",
        "data"
      ]
    }
  }
}