{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "Location Group",
    "description": "Enable user to perform CRUD operations on location group.",
    "license": {
      "name": "MIT",
      "url": "http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT"
    }
  },
  "host": "localhost:8000",
  "basePath": "/core/locationgroup",
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/getAll": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "getAll",
        "tags": [
          "Misc"
        ],
        "operationId": "getAll",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/GetAllRequest"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "tenantId",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "userId",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "email",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/GetAllResponse"
            },
            "examples": {
              "application/json": {
                "status": 200,
                "message": "All data retrieved",
                "data": [
                  {
                    "id": 3,
                    "effBegin": "2017-10-01",
                    "effEnd": "2017-12-01",
                    "code": "LG1",
                    "name": "Location Group 1"
                  },
                  {
                    "id": 7,
                    "effBegin": "2017-10-01",
                    "effEnd": "2017-12-01",
                    "code": "LG1",
                    "name": "Location Group 1"
                  },
                  {
                    "id": 8,
                    "effBegin": "2017-10-01",
                    "effEnd": "2017-12-01",
                    "code": "LG1",
                    "name": "Location Group 1"
                  },
                  {
                    "id": 9,
                    "effBegin": "2017-10-01",
                    "effEnd": "2017-12-01",
                    "code": "LG1",
                    "name": "Location Group 1"
                  },
                  {
                    "id": 10,
                    "effBegin": "2017-10-01",
                    "effEnd": "2017-12-01",
                    "code": "LG1",
                    "name": "Location Group 1"
                  },
                  {
                    "id": 11,
                    "effBegin": "2017-10-01",
                    "effEnd": "2017-12-01",
                    "code": "LG1",
                    "name": "Location Group 1"
                  },
                  {
                    "id": 19,
                    "effBegin": "2017-10-01",
                    "effEnd": "2017-12-01",
                    "code": "LG1",
                    "name": "Location Group 1"
                  },
                  {
                    "id": 20,
                    "effBegin": "2017-10-01",
                    "effEnd": "2017-12-01",
                    "code": "LG1",
                    "name": "Location Group 1"
                  },
                  {
                    "id": 21,
                    "effBegin": "2017-10-01",
                    "effEnd": "2017-12-01",
                    "code": "LG1",
                    "name": "Location Group 1"
                  },
                  {
                    "id": 6,
                    "effBegin": "2017-10-01",
                    "effEnd": "2017-12-01",
                    "code": "LG1",
                    "name": "Location Group 1"
                  }
                ]
              }
            }
          }
        },
        "security": [],
        "x-unitTests": [
          {
            "request": {
              "method": "POST",
              "uri": "/getAll",
              "headers": {
                "Content-Type": "application/json",
                "tenantId": "1000000000",
                "userId": "1",
                "email": "user1@mail.com"
              },
              "body": "{\n\t\"companyId\": 17751\n}"
            },
            "expectedResponse": {
              "x-allowExtraHeaders": true,
              "x-bodyMatchMode": "RAW",
              "x-arrayOrderedMatching": false,
              "x-arrayCheckCount": false,
              "x-matchResponseSchema": true,
              "headers": {
                "Cache-Control": "no-cache, private",
                "Connection": "keep-alive",
                "Content-Language": "en",
                "Content-Type": "application/json",
                "Date": "Fri, 29 Sep 2017 08:53:03 GMT",
                "Server": "nginx",
                "Transfer-Encoding": "chunked",
                "Via": "kong/0.11.0",
                "X-Kong-Proxy-Latency": "1",
                "X-Kong-Upstream-Latency": "120",
                "X-Powered-By": "PHP/7.1.9"
              },
              "body": "{\"status\":200,\"message\":\"All data retrieved\",\"data\":[{\"id\":3,\"effBegin\":\"2017-10-01\",\"effEnd\":\"2017-12-01\",\"code\":\"LG1\",\"name\":\"Location Group 1\"},{\"id\":7,\"effBegin\":\"2017-10-01\",\"effEnd\":\"2017-12-01\",\"code\":\"LG1\",\"name\":\"Location Group 1\"},{\"id\":8,\"effBegin\":\"2017-10-01\",\"effEnd\":\"2017-12-01\",\"code\":\"LG1\",\"name\":\"Location Group 1\"},{\"id\":9,\"effBegin\":\"2017-10-01\",\"effEnd\":\"2017-12-01\",\"code\":\"LG1\",\"name\":\"Location Group 1\"},{\"id\":10,\"effBegin\":\"2017-10-01\",\"effEnd\":\"2017-12-01\",\"code\":\"LG1\",\"name\":\"Location Group 1\"},{\"id\":11,\"effBegin\":\"2017-10-01\",\"effEnd\":\"2017-12-01\",\"code\":\"LG1\",\"name\":\"Location Group 1\"},{\"id\":19,\"effBegin\":\"2017-10-01\",\"effEnd\":\"2017-12-01\",\"code\":\"LG1\",\"name\":\"Location Group 1\"},{\"id\":20,\"effBegin\":\"2017-10-01\",\"effEnd\":\"2017-12-01\",\"code\":\"LG1\",\"name\":\"Location Group 1\"},{\"id\":21,\"effBegin\":\"2017-10-01\",\"effEnd\":\"2017-12-01\",\"code\":\"LG1\",\"name\":\"Location Group 1\"},{\"id\":6,\"effBegin\":\"2017-10-01\",\"effEnd\":\"2017-12-01\",\"code\":\"LG1\",\"name\":\"Location Group 1\"}]}"
            },
            "x-testShouldPass": true,
            "x-testEnabled": true,
            "x-testName": "getAll",
            "x-testDescription": "TODO: Add Description"
          }
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/getOne": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "getOne",
        "tags": [
          "Misc"
        ],
        "operationId": "getOne",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/GetOneRequest"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "tenantId",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "userId",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "email",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/GetOneResponse"
            },
            "examples": {
              "application/json": {
                "status": 200,
                "message": "Data retrieved",
                "data": {
                  "id": 23,
                  "locationDetail": [
                    {
                      "locationId": 3,
                      "locationName": "Kantor Pusat",
                      "locationAddress": "ini alamatnya"
                    },
                    {
                      "locationId": 7,
                      "locationName": "Kantor Pusat",
                      "locationAddress": "ini alamatnya bung"
                    }
                  ],
                  "effBegin": "2017-10-01",
                  "effEnd": "2017-12-01",
                  "code": "LG1",
                  "name": "Location Group 1"
                }
              }
            }
          }
        },
        "security": [],
        "x-unitTests": [
          {
            "request": {
              "method": "POST",
              "uri": "/getOne",
              "headers": {
                "Content-Type": "application/json",
                "tenantId": "1000000000",
                "userId": "1",
                "email": "user1@mail.com"
              },
              "body": "{\n\t\"companyId\": 17751,\n\t\"id\": 23\n}"
            },
            "expectedResponse": {
              "x-allowExtraHeaders": true,
              "x-bodyMatchMode": "RAW",
              "x-arrayOrderedMatching": false,
              "x-arrayCheckCount": false,
              "x-matchResponseSchema": true,
              "headers": {
                "Cache-Control": "no-cache, private",
                "Connection": "keep-alive",
                "Content-Language": "en",
                "Content-Type": "application/json",
                "Date": "Mon, 02 Oct 2017 09:05:18 GMT",
                "Server": "nginx",
                "Transfer-Encoding": "chunked",
                "Via": "kong/0.11.0",
                "X-Kong-Proxy-Latency": "0",
                "X-Kong-Upstream-Latency": "70",
                "X-Powered-By": "PHP/7.1.9"
              },
              "body": "{\"status\":200,\"message\":\"Data retrieved\",\"data\":{\"id\":23,\"locationDetail\":[{\"locationId\":3,\"locationName\":\"Kantor Pusat\",\"locationAddress\":\"ini alamatnya\"},{\"locationId\":7,\"locationName\":\"Kantor Pusat\",\"locationAddress\":\"ini alamatnya bung\"}],\"effBegin\":\"2017-10-01\",\"effEnd\":\"2017-12-01\",\"code\":\"LG1\",\"name\":\"Location Group 1\"}}"
            },
            "x-testShouldPass": true,
            "x-testEnabled": true,
            "x-testName": "getOne",
            "x-testDescription": "TODO: Add Description"
          }
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/save": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "save",
        "tags": [
          "Misc"
        ],
        "operationId": "save",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/SaveRequest"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "tenantId",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "userId",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "email",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/SaveResponse"
            },
            "examples": {
              "application/json": {
                "status": 200,
                "message": "Data saved",
                "data": {
                  "id": 23
                }
              }
            }
          }
        },
        "security": [],
        "x-unitTests": [
          {
            "request": {
              "method": "POST",
              "uri": "/save",
              "headers": {
                "Content-Type": "application/json",
                "tenantId": "1000000000",
                "userId": "1",
                "email": "user1@mail.com"
              },
              "body": "{\n\t\"companyId\": 17751,\n\t\"effBegin\": \"2017-10-1\",\n\t\"effEnd\": \"2017-12-1\",\n\t\"code\": \"LG1\",\n\t\"name\": \"Location Group 1\",\n\t\"locationDetail\": [\n\t\t{\n\t\t\t\"id\": 3\n\t\t},\n\t\t{\n\t\t\t\"id\": 7\n\t\t}\n\t]\n}"
            },
            "expectedResponse": {
              "x-allowExtraHeaders": true,
              "x-bodyMatchMode": "RAW",
              "x-arrayOrderedMatching": false,
              "x-arrayCheckCount": false,
              "x-matchResponseSchema": true,
              "headers": {
                "Cache-Control": "no-cache, private",
                "Connection": "keep-alive",
                "Content-Language": "en",
                "Content-Type": "application/json",
                "Date": "Fri, 29 Sep 2017 08:55:41 GMT",
                "Server": "nginx",
                "Transfer-Encoding": "chunked",
                "Via": "kong/0.11.0",
                "X-Kong-Proxy-Latency": "1",
                "X-Kong-Upstream-Latency": "163",
                "X-Powered-By": "PHP/7.1.9"
              },
              "body": "{\"status\":200,\"message\":\"Data saved\",\"data\":{\"id\":23}}"
            },
            "x-testShouldPass": true,
            "x-testEnabled": true,
            "x-testName": "save",
            "x-testDescription": "TODO: Add Description"
          }
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/update": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "update",
        "tags": [
          "Misc"
        ],
        "operationId": "update",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/UpdateRequest"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "tenantId",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "userId",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "email",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/UpdateResponse"
            },
            "examples": {}
          }
        },
        "security": [],
        "x-unitTests": [],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/delete": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "delete",
        "tags": [
          "Misc"
        ],
        "operationId": "delete",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/DeleteRequest"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "tenantId",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "userId",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "email",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/DeleteResponse"
            },
            "examples": {}
          }
        },
        "security": [],
        "x-unitTests": [],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    }
  },
  "definitions": {
    "GetAllRequest": {
      "title": "getAllRequest",
      "example": {
        "companyId": 17751
      },
      "type": "object",
      "properties": {
        "companyId": {
          "description": "",
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "companyId"
      ]
    },
    "GetAllResponse": {
      "title": "getAllResponse",
      "example": {
        "status": 200,
        "message": "All data retrieved",
        "data": [
          {
            "id": 3,
            "effBegin": "2017-10-01",
            "effEnd": "2017-12-01",
            "code": "LG1",
            "name": "Location Group 1"
          },
          {
            "id": 7,
            "effBegin": "2017-10-01",
            "effEnd": "2017-12-01",
            "code": "LG1",
            "name": "Location Group 1"
          },
          {
            "id": 8,
            "effBegin": "2017-10-01",
            "effEnd": "2017-12-01",
            "code": "LG1",
            "name": "Location Group 1"
          },
          {
            "id": 9,
            "effBegin": "2017-10-01",
            "effEnd": "2017-12-01",
            "code": "LG1",
            "name": "Location Group 1"
          },
          {
            "id": 10,
            "effBegin": "2017-10-01",
            "effEnd": "2017-12-01",
            "code": "LG1",
            "name": "Location Group 1"
          },
          {
            "id": 11,
            "effBegin": "2017-10-01",
            "effEnd": "2017-12-01",
            "code": "LG1",
            "name": "Location Group 1"
          },
          {
            "id": 19,
            "effBegin": "2017-10-01",
            "effEnd": "2017-12-01",
            "code": "LG1",
            "name": "Location Group 1"
          },
          {
            "id": 20,
            "effBegin": "2017-10-01",
            "effEnd": "2017-12-01",
            "code": "LG1",
            "name": "Location Group 1"
          },
          {
            "id": 21,
            "effBegin": "2017-10-01",
            "effEnd": "2017-12-01",
            "code": "LG1",
            "name": "Location Group 1"
          },
          {
            "id": 6,
            "effBegin": "2017-10-01",
            "effEnd": "2017-12-01",
            "code": "LG1",
            "name": "Location Group 1"
          }
        ]
      },
      "type": "object",
      "properties": {
        "status": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "description": "",
          "type": "string"
        },
        "data": {
          "description": "",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Datum"
          }
        }
      },
      "required": [
        "status",
        "message",
        "data"
      ]
    },
    "Datum": {
      "title": "Datum",
      "type": "object",
      "properties": {
        "id": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "effBegin": {
          "description": "",
          "type": "string"
        },
        "effEnd": {
          "description": "",
          "type": "string"
        },
        "code": {
          "description": "",
          "type": "string"
        },
        "name": {
          "description": "",
          "type": "string"
        }
      },
      "required": [
        "id",
        "effBegin",
        "effEnd",
        "code",
        "name"
      ]
    },
    "GetOneRequest": {
      "title": "getOneRequest",
      "example": {
        "companyId": 17751,
        "id": 23
      },
      "type": "object",
      "properties": {
        "companyId": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "id": {
          "description": "",
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "companyId",
        "id"
      ]
    },
    "GetOneResponse": {
      "title": "getOneResponse",
      "example": {
        "status": 200,
        "message": "Data retrieved",
        "data": {
          "id": 23,
          "locationDetail": [
            {
              "locationId": 3,
              "locationName": "Kantor Pusat",
              "locationAddress": "ini alamatnya"
            },
            {
              "locationId": 7,
              "locationName": "Kantor Pusat",
              "locationAddress": "ini alamatnya bung"
            }
          ],
          "effBegin": "2017-10-01",
          "effEnd": "2017-12-01",
          "code": "LG1",
          "name": "Location Group 1"
        }
      },
      "type": "object",
      "properties": {
        "status": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "description": "",
          "type": "string"
        },
        "data": {
          "$ref": "#/definitions/Data"
        }
      },
      "required": [
        "status",
        "message",
        "data"
      ]
    },
    "Data": {
      "title": "Data",
      "type": "object",
      "properties": {
        "id": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "locationDetail": {
          "description": "",
          "type": "array",
          "items": {
            "$ref": "#/definitions/LocationDetail"
          }
        },
        "effBegin": {
          "description": "",
          "type": "string"
        },
        "effEnd": {
          "description": "",
          "type": "string"
        },
        "code": {
          "description": "",
          "type": "string"
        },
        "name": {
          "description": "",
          "type": "string"
        }
      },
      "required": [
        "id",
        "locationDetail",
        "effBegin",
        "effEnd",
        "code",
        "name"
      ]
    },
    "LocationDetail": {
      "title": "LocationDetail",
      "type": "object",
      "properties": {
        "locationId": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "locationName": {
          "description": "",
          "type": "string"
        },
        "locationAddress": {
          "description": "",
          "type": "string"
        }
      },
      "required": [
        "locationId",
        "locationName",
        "locationAddress"
      ]
    },
    "SaveRequest": {
      "title": "saveRequest",
      "example": {
        "companyId": 17751,
        "effBegin": "2017-10-1",
        "effEnd": "2017-12-1",
        "code": "LG1",
        "name": "Location Group 1",
        "locationDetail": [
          {
            "id": 3
          },
          {
            "id": 7
          }
        ]
      },
      "type": "object",
      "properties": {
        "companyId": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "effBegin": {
          "description": "",
          "type": "string"
        },
        "effEnd": {
          "description": "",
          "type": "string"
        },
        "code": {
          "description": "",
          "type": "string"
        },
        "name": {
          "description": "",
          "type": "string"
        },
        "locationDetail": {
          "description": "",
          "type": "array",
          "items": {
            "$ref": "#/definitions/LocationDetail8"
          }
        }
      },
      "required": [
        "companyId",
        "effBegin",
        "effEnd",
        "code",
        "name",
        "locationDetail"
      ]
    },
    "LocationDetail8": {
      "title": "LocationDetail8",
      "type": "object",
      "properties": {
        "id": {
          "description": "",
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "id"
      ]
    },
    "SaveResponse": {
      "title": "saveResponse",
      "example": {
        "status": 200,
        "message": "Data saved",
        "data": {
          "id": 23
        }
      },
      "type": "object",
      "properties": {
        "status": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "description": "",
          "type": "string"
        },
        "data": {
          "$ref": "#/definitions/Data10"
        }
      },
      "required": [
        "status",
        "message",
        "data"
      ]
    },
    "Data10": {
      "title": "Data10",
      "type": "object",
      "properties": {
        "id": {
          "description": "",
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "id"
      ]
    },
    "UpdateRequest": {
      "title": "updateRequest",
      "example": {
        "companyId": 17751,
        "id": 6,
        "effBegin": "2017-10-1",
        "effEnd": "2017-12-1",
        "code": "LG1",
        "name": "Location Group 1",
        "locationDetail": [
          {
            "id": 4
          },
          {
            "id": 5
          }
        ]
      },
      "type": "object",
      "properties": {
        "companyId": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "id": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "effBegin": {
          "description": "",
          "type": "string"
        },
        "effEnd": {
          "description": "",
          "type": "string"
        },
        "code": {
          "description": "",
          "type": "string"
        },
        "name": {
          "description": "",
          "type": "string"
        },
        "locationDetail": {
          "description": "",
          "type": "array",
          "items": {
            "$ref": "#/definitions/LocationDetail8"
          }
        }
      },
      "required": [
        "companyId",
        "id",
        "effBegin",
        "effEnd",
        "code",
        "name",
        "locationDetail"
      ]
    },
    "UpdateResponse": {
      "title": "updateResponse",
      "type": "object",
      "properties": {
        "status": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "description": "",
          "type": "string"
        },
        "data": {
          "description": "",
          "type": "string"
        }
      },
      "required": [
        "status",
        "message",
        "data"
      ]
    },
    "DeleteRequest": {
      "title": "deleteRequest",
      "example": {
        "companyId": 17751,
        "id": 5
      },
      "type": "object",
      "properties": {
        "companyId": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "id": {
          "description": "",
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "companyId",
        "id"
      ]
    },
    "DeleteResponse": {
      "title": "deleteResponse",
      "type": "object",
      "properties": {
        "status": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "description": "",
          "type": "string"
        },
        "data": {
          "description": "",
          "type": "string"
        }
      },
      "required": [
        "status",
        "message",
        "data"
      ]
    }
  }
}