{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "Organization Structure",
    "description": "Enable user to perform CRUD operations on organization structure.",
    "license": {
      "name": "MIT",
      "url": "http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT"
    }
  },
  "host": "localhost:8000",
  "basePath": "/core",
  "securityDefinitions": {
    "auth": {
      "type": "oauth2",
      "flow": "implicit",
      "authorizationUrl": "http://localhost:8000/core",
      "scopes": {}
    }
  },
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/orgstructure/getAll": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "getAll",
        "tags": [
          "Misc"
        ],
        "operationId": "getAll",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/GetAllRequest"
            }
          },
          {
            "name": "tenantId",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "userId",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "email",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/GetAllResponse"
            },
            "examples": {
              "application/json": {
                "status": 200,
                "message": "All data retrieved",
                "data": [
                  {
                    "id": 1,
                    "effBegin": "2017-10-01",
                    "effEnd": "2018-10-01",
                    "name": "Structure 1",
                    "description": "This is a structure",
                    "isPrimary": true
                  }
                ]
              }
            }
          }
        },
        "security": [],
        "x-unitTests": [
          {
            "request": {
              "method": "POST",
              "uri": "/orgstructure/getAll",
              "headers": {
                "Content-Type": "application/json",
                "tenantId": "1000000000",
                "userId": "1",
                "email": "user1@mail.com"
              },
              "body": "{\n\t\"companyId\": 17751\n}"
            },
            "expectedResponse": {
              "x-allowExtraHeaders": true,
              "x-bodyMatchMode": "RAW",
              "x-arrayOrderedMatching": false,
              "x-arrayCheckCount": false,
              "x-matchResponseSchema": true,
              "headers": {
                "Cache-Control": "no-cache, private",
                "Connection": "keep-alive",
                "Content-Language": "en",
                "Content-Type": "application/json",
                "Date": "Tue, 03 Oct 2017 08:44:20 GMT",
                "Server": "nginx",
                "Transfer-Encoding": "chunked",
                "Via": "kong/0.11.0",
                "X-Kong-Proxy-Latency": "0",
                "X-Kong-Upstream-Latency": "70",
                "X-Powered-By": "PHP/7.1.9"
              },
              "body": "{\"status\":200,\"message\":\"All data retrieved\",\"data\":[{\"id\":1,\"effBegin\":\"2017-10-01\",\"effEnd\":\"2018-10-01\",\"name\":\"Structure 1\",\"description\":\"This is a structure\",\"isPrimary\":true}]}"
            },
            "x-testShouldPass": true,
            "x-testEnabled": true,
            "x-testName": "getAll",
            "x-testDescription": "TODO: Add Description"
          }
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/orgStructure/getOne": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "getOne",
        "tags": [
          "Misc"
        ],
        "operationId": "getOne",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/GetOneRequest"
            }
          },
          {
            "name": "tenantId",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "userId",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "email",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Origin",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/GetOneResponse"
            },
            "examples": {}
          }
        },
        "security": [
          {
            "auth": []
          }
        ],
        "x-unitTests": [],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/orgstructure/save": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "save",
        "tags": [
          "Misc"
        ],
        "operationId": "save",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/SaveRequest"
            }
          },
          {
            "name": "tenantId",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "userId",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "email",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/SaveResponse"
            },
            "examples": {
              "application/json": {
                "status": 200,
                "message": "Data saved",
                "data": {
                  "id": 1
                }
              }
            }
          }
        },
        "security": [],
        "x-unitTests": [
          {
            "request": {
              "method": "POST",
              "uri": "/orgstructure/save",
              "headers": {
                "Content-Type": "application/json",
                "tenantId": "1000000000",
                "userId": "1",
                "email": "user1@mail.com"
              },
              "body": "{\n\t\"companyId\": 17751,\n\t\"effBegin\": \"2017-10-1\",\n\t\"effEnd\": \"2018-10-1\",\n\t\"name\": \"Structure 1\",\n\t\"description\": \"This is a structure\",\n\t\"isPrimary\": true,\n\t\"orgStructureHierarchy\": [\n\t\t{\n\t\t\t\"parentId\": 0,\n\t\t\t\"unitId\": 1\n\t\t},\n\t\t{\n\t\t\t\"parentId\": 1,\n\t\t\t\"unitId\": 2\n\t\t},\n\t\t{\n\t\t\t\"parentId\": 1,\n\t\t\t\"unitId\": 3\n\t\t},\n\t\t{\n\t\t\t\"parentId\": 2,\n\t\t\t\"unitId\": 4\n\t\t}\n\t]\n}"
            },
            "expectedResponse": {
              "x-allowExtraHeaders": true,
              "x-bodyMatchMode": "RAW",
              "x-arrayOrderedMatching": false,
              "x-arrayCheckCount": false,
              "x-matchResponseSchema": true,
              "headers": {
                "Cache-Control": "no-cache, private",
                "Connection": "keep-alive",
                "Content-Language": "en",
                "Content-Type": "application/json",
                "Date": "Tue, 03 Oct 2017 08:43:46 GMT",
                "Server": "nginx",
                "Transfer-Encoding": "chunked",
                "Via": "kong/0.11.0",
                "X-Kong-Proxy-Latency": "0",
                "X-Kong-Upstream-Latency": "571",
                "X-Powered-By": "PHP/7.1.9"
              },
              "body": "{\"status\":200,\"message\":\"Data saved\",\"data\":{\"id\":1}}"
            },
            "x-testShouldPass": true,
            "x-testEnabled": true,
            "x-testName": "save",
            "x-testDescription": "TODO: Add Description"
          }
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/orgstructure/update": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "update",
        "tags": [
          "Misc"
        ],
        "operationId": "update",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/UpdateRequest"
            }
          },
          {
            "name": "tenantId",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "userId",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "email",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "security": [],
        "x-unitTests": [
          {
            "request": {
              "method": "POST",
              "uri": "/orgstructure/update",
              "headers": {
                "Content-Type": "application/json",
                "tenantId": "1000000000",
                "userId": "1",
                "email": "user1@mail.com"
              },
              "body": "{\n\t\"companyId\": 17751,\n\t\"id\": 1,\n\t\"effBegin\": \"2017-10-1\",\n\t\"effEnd\": \"2018-10-1\",\n\t\"name\": \"Structure 1\",\n\t\"description\": \"This is a structure\",\n\t\"isPrimary\": true,\n\t\"orgStructureHierarchy\": [\n\t\t{\n\t\t\t\"parentId\": 0,\n\t\t\t\"unitId\": 1\n\t\t},\n\t\t{\n\t\t\t\"parentId\": 1,\n\t\t\t\"unitId\": 2\n\t\t},\n\t\t{\n\t\t\t\"parentId\": 1,\n\t\t\t\"unitId\": 3\n\t\t},\n\t\t{\n\t\t\t\"parentId\": 2,\n\t\t\t\"unitId\": 4\n\t\t},\n\t\t{\n\t\t\t\"parentId\": 0,\n\t\t\t\"unitId\": 5\n\t\t},\n\t\t{\n\t\t\t\"parentId\": 5,\n\t\t\t\"unitId\": 6\n\t\t},\n\t\t{\n\t\t\t\"parentId\": 5,\n\t\t\t\"unitId\": 7\n\t\t},\n\t\t{\n\t\t\t\"parentId\": 3,\n\t\t\t\"unitId\": 8\n\t\t},\n\t\t{\n\t\t\t\"parentId\": 3,\n\t\t\t\"unitId\": 9\n\t\t},\n\t\t{\n\t\t\t\"parentId\": 5,\n\t\t\t\"unitId\": 10\n\t\t}\n\t]\n}"
            },
            "expectedResponse": {
              "x-allowExtraHeaders": true,
              "x-bodyMatchMode": "NONE",
              "x-arrayOrderedMatching": false,
              "x-arrayCheckCount": false,
              "x-matchResponseSchema": true,
              "headers": {}
            },
            "x-testShouldPass": true,
            "x-testEnabled": true,
            "x-testName": "update",
            "x-testDescription": "TODO: Add Description"
          }
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/orgstructure/delete": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "delete",
        "tags": [
          "Misc"
        ],
        "operationId": "delete",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/DeleteRequest"
            }
          },
          {
            "name": "tenantId",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "userId",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "email",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/DeleteResponse"
            },
            "examples": {}
          }
        },
        "security": [],
        "x-unitTests": [],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    }
  },
  "definitions": {
    "GetAllRequest": {
      "title": "getAllRequest",
      "example": {
        "companyId": 17751
      },
      "type": "object",
      "properties": {
        "companyId": {
          "description": "",
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "companyId"
      ]
    },
    "GetAllResponse": {
      "title": "getAllResponse",
      "example": {
        "status": 200,
        "message": "All data retrieved",
        "data": [
          {
            "id": 1,
            "effBegin": "2017-10-01",
            "effEnd": "2018-10-01",
            "name": "Structure 1",
            "description": "This is a structure",
            "isPrimary": true
          }
        ]
      },
      "type": "object",
      "properties": {
        "status": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "description": "",
          "type": "string"
        },
        "data": {
          "description": "",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Datum"
          }
        }
      },
      "required": [
        "status",
        "message",
        "data"
      ]
    },
    "Datum": {
      "title": "Datum",
      "type": "object",
      "properties": {
        "id": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "effBegin": {
          "description": "",
          "type": "string"
        },
        "effEnd": {
          "description": "",
          "type": "string"
        },
        "name": {
          "description": "",
          "type": "string"
        },
        "description": {
          "description": "",
          "type": "string"
        },
        "isPrimary": {
          "description": "",
          "type": "boolean"
        }
      },
      "required": [
        "id",
        "effBegin",
        "effEnd",
        "name",
        "description",
        "isPrimary"
      ]
    },
    "GetOneRequest": {
      "title": "getOneRequest",
      "example": {
        "companyId": 1900000000,
        "id": 3
      },
      "type": "object",
      "properties": {
        "companyId": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "id": {
          "description": "",
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "companyId",
        "id"
      ]
    },
    "GetOneResponse": {
      "title": "getOneResponse",
      "type": "object",
      "properties": {
        "status": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "description": "",
          "type": "string"
        },
        "data": {
          "$ref": "#/definitions/Data"
        }
      },
      "required": [
        "status",
        "message",
        "data"
      ]
    },
    "Data": {
      "title": "Data",
      "type": "object",
      "properties": {
        "id": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "effBegin": {
          "description": "",
          "type": "string"
        },
        "effEnd": {
          "description": "",
          "type": "string"
        },
        "name": {
          "description": "",
          "type": "string"
        },
        "description": {
          "description": "",
          "type": "string"
        },
        "isPrimary": {
          "description": "",
          "type": "boolean"
        },
        "hierarchy": {
          "description": "",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Hierarchy"
          }
        }
      },
      "required": [
        "id",
        "effBegin",
        "effEnd",
        "name",
        "description",
        "isPrimary",
        "hierarchy"
      ]
    },
    "Hierarchy": {
      "title": "Hierarchy",
      "type": "object",
      "properties": {
        "unitId": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "unitName": {
          "description": "",
          "type": "string"
        },
        "houId": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "houFirstName": {
          "description": "",
          "type": "string"
        },
        "houLastName": {
          "description": "",
          "type": "string"
        },
        "houPositionId": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "houPositionCode": {
          "description": "",
          "type": "string"
        },
        "parentId": {
          "description": "",
          "type": "string"
        },
        "subNodes": {
          "description": "",
          "type": "array",
          "items": {
            "$ref": "#/definitions/SubNode"
          }
        }
      },
      "required": [
        "unitId",
        "unitName",
        "houId",
        "houFirstName",
        "houLastName",
        "houPositionId",
        "houPositionCode",
        "parentId",
        "subNodes"
      ]
    },
    "SubNode": {
      "title": "SubNode",
      "type": "object",
      "properties": {
        "unitId": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "unitName": {
          "description": "",
          "type": "string"
        },
        "houId": {
          "description": "",
          "type": "string"
        },
        "houFirstName": {
          "description": "",
          "type": "string"
        },
        "houLastName": {
          "description": "",
          "type": "string"
        },
        "houPositionId": {
          "description": "",
          "type": "string"
        },
        "houPositionCode": {
          "description": "",
          "type": "string"
        },
        "parentId": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "subNodes": {
          "description": "",
          "type": "array",
          "items": {
            "$ref": "#/definitions/SubNode8"
          }
        }
      },
      "required": [
        "unitId",
        "unitName",
        "houId",
        "houFirstName",
        "houLastName",
        "houPositionId",
        "houPositionCode",
        "parentId",
        "subNodes"
      ]
    },
    "SubNode8": {
      "title": "SubNode8",
      "type": "object",
      "properties": {
        "unitId": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "unitName": {
          "description": "",
          "type": "string"
        },
        "houId": {
          "description": "",
          "type": "string"
        },
        "houFirstName": {
          "description": "",
          "type": "string"
        },
        "houLastName": {
          "description": "",
          "type": "string"
        },
        "houPositionId": {
          "description": "",
          "type": "string"
        },
        "houPositionCode": {
          "description": "",
          "type": "string"
        },
        "parentId": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "subNodes": {
          "description": "",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "unitId",
        "unitName",
        "houId",
        "houFirstName",
        "houLastName",
        "houPositionId",
        "houPositionCode",
        "parentId",
        "subNodes"
      ]
    },
    "SaveRequest": {
      "title": "saveRequest",
      "example": {
        "companyId": 17751,
        "effBegin": "2017-10-1",
        "effEnd": "2018-10-1",
        "name": "Structure 1",
        "description": "This is a structure",
        "isPrimary": true,
        "orgStructureHierarchy": [
          {
            "parentId": 0,
            "unitId": 1
          },
          {
            "parentId": 1,
            "unitId": 2
          },
          {
            "parentId": 1,
            "unitId": 3
          },
          {
            "parentId": 2,
            "unitId": 4
          }
        ]
      },
      "type": "object",
      "properties": {
        "companyId": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "effBegin": {
          "description": "",
          "type": "string"
        },
        "effEnd": {
          "description": "",
          "type": "string"
        },
        "name": {
          "description": "",
          "type": "string"
        },
        "description": {
          "description": "",
          "type": "string"
        },
        "isPrimary": {
          "description": "",
          "type": "boolean"
        },
        "orgStructureHierarchy": {
          "description": "",
          "type": "array",
          "items": {
            "$ref": "#/definitions/OrgStructureHierarchy"
          }
        }
      },
      "required": [
        "companyId",
        "effBegin",
        "effEnd",
        "name",
        "description",
        "isPrimary",
        "orgStructureHierarchy"
      ]
    },
    "OrgStructureHierarchy": {
      "title": "OrgStructureHierarchy",
      "type": "object",
      "properties": {
        "parentId": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "unitId": {
          "description": "",
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "parentId",
        "unitId"
      ]
    },
    "SaveResponse": {
      "title": "saveResponse",
      "example": {
        "status": 200,
        "message": "Data saved",
        "data": {
          "id": 1
        }
      },
      "type": "object",
      "properties": {
        "status": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "description": "",
          "type": "string"
        },
        "data": {
          "$ref": "#/definitions/Data12"
        }
      },
      "required": [
        "status",
        "message",
        "data"
      ]
    },
    "Data12": {
      "title": "Data12",
      "type": "object",
      "properties": {
        "id": {
          "description": "",
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "id"
      ]
    },
    "UpdateRequest": {
      "title": "updateRequest",
      "example": {
        "companyId": 17751,
        "id": 1,
        "effBegin": "2017-10-1",
        "effEnd": "2018-10-1",
        "name": "Structure 1",
        "description": "This is a structure",
        "isPrimary": true,
        "orgStructureHierarchy": [
          {
            "parentId": 0,
            "unitId": 1
          },
          {
            "parentId": 1,
            "unitId": 2
          },
          {
            "parentId": 1,
            "unitId": 3
          },
          {
            "parentId": 2,
            "unitId": 4
          },
          {
            "parentId": 0,
            "unitId": 5
          },
          {
            "parentId": 5,
            "unitId": 6
          },
          {
            "parentId": 5,
            "unitId": 7
          },
          {
            "parentId": 3,
            "unitId": 8
          },
          {
            "parentId": 3,
            "unitId": 9
          },
          {
            "parentId": 5,
            "unitId": 10
          }
        ]
      },
      "type": "object",
      "properties": {
        "companyId": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "id": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "effBegin": {
          "description": "",
          "type": "string"
        },
        "effEnd": {
          "description": "",
          "type": "string"
        },
        "name": {
          "description": "",
          "type": "string"
        },
        "description": {
          "description": "",
          "type": "string"
        },
        "isPrimary": {
          "description": "",
          "type": "boolean"
        },
        "orgStructureHierarchy": {
          "description": "",
          "type": "array",
          "items": {
            "$ref": "#/definitions/OrgStructureHierarchy"
          }
        }
      },
      "required": [
        "companyId",
        "id",
        "effBegin",
        "effEnd",
        "name",
        "description",
        "isPrimary",
        "orgStructureHierarchy"
      ]
    },
    "DeleteRequest": {
      "title": "deleteRequest",
      "example": {
        "companyId": 17751,
        "id": 1
      },
      "type": "object",
      "properties": {
        "companyId": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "id": {
          "description": "",
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "companyId",
        "id"
      ]
    },
    "DeleteResponse": {
      "title": "deleteResponse",
      "type": "object",
      "properties": {
        "status": {
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "description": "",
          "type": "string"
        },
        "data": {
          "description": "",
          "type": "string"
        }
      },
      "required": [
        "status",
        "message",
        "data"
      ]
    }
  }
}